version: 1

before:
  hooks:
    - go mod tidy
    - make pre-build

builds:
  - main: ./cmd/kubectl-portal
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64

archives:
  - format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
