apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: portal
spec:
  version: v${VERSION}
  homepage: https://github.com/federicotdn/kubectl-portal
  shortDescription: An HTTP proxy for connecting to stuff inside your cluster.
  description: |
    A kubectl plugin that launches an HTTP proxy, enabling you to make
    requests to Services, Pods and any other host reachable from within
    your cluster.
  platforms:
  - selector:
      matchLabels:
        os: darwin
        arch: amd64
    bin: kubectl-portal
    uri: https://github.com/federicotdn/kubectl-portal/releases/download/v${VERSION}/kubectl-portal-darwin-amd64.tar.gz
    sha256: ${SHA256_DARWIN_AMD64}
  - selector:
      matchLabels:
        os: darwin
        arch: arm64
    bin: kubectl-portal
    uri: https://github.com/federicotdn/kubectl-portal/releases/download/v${VERSION}/kubectl-portal-darwin-arm64.tar.gz
    sha256: ${SHA256_DARWIN_ARM64}
  - selector:
      matchLabels:
        os: linux
        arch: amd64
    bin: kubectl-portal
    uri: https://github.com/federicotdn/kubectl-portal/releases/download/v${VERSION}/kubectl-portal-linux-amd64.tar.gz
    sha256: ${SHA256_LINUX_AMD64}
  - selector:
      matchLabels:
        os: linux
        arch: arm64
    bin: kubectl-portal
    uri: https://github.com/federicotdn/kubectl-portal/releases/download/v${VERSION}/kubectl-portal-linux-arm64.tar.gz
    sha256: ${SHA256_LINUX_ARM64}
  - selector:
      matchLabels:
        os: windows
        arch: amd64
    bin: kubectl-portal.exe
    uri: https://github.com/federicotdn/kubectl-portal/releases/download/v${VERSION}/kubectl-portal-windows-amd64.tar.gz
    sha256: ${SHA256_WINDOWS_AMD64}
