apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: portal
spec:
  version: {{ .TagName }}
  homepage: https://github.com/federicotdn/kubectl-portal
  shortDescription: An HTTP proxy for connecting to stuff inside your cluster.
  description: |
    A kubectl plugin that launches an HTTP proxy, enabling you to make
    requests to Services, Pods and any other host reachable from within
    your cluster.
  platforms:
  - selector:
      matchLabels:
        os: darwin
        arch: amd64
    bin: kubectl-portal
    {{addURIAndSha "https://github.com/federicotdn/kubectl-portal/releases/download/{{ .TagName }}/kubectl-portal_{{ .TagName }}_darwin_amd64.tar.gz" .TagName }}
  - selector:
      matchLabels:
        os: darwin
        arch: arm64
    bin: kubectl-portal
        {{addURIAndSha "https://github.com/federicotdn/kubectl-portal/releases/download/{{ .TagName }}/kubectl-portal_{{ .TagName }}_darwin_arm64.tar.gz" .TagName }}
  - selector:
      matchLabels:
        os: linux
        arch: amd64
    bin: kubectl-portal
    {{addURIAndSha "https://github.com/federicotdn/kubectl-portal/releases/download/{{ .TagName }}/kubectl-portal_{{ .TagName }}_linux_amd64.tar.gz" .TagName }}
  - selector:
      matchLabels:
        os: linux
        arch: arm64
    bin: kubectl-portal
    {{addURIAndSha "https://github.com/federicotdn/kubectl-portal/releases/download/{{ .TagName }}/kubectl-portal_{{ .TagName }}_linux_arm64.tar.gz" .TagName }}
  - selector:
      matchLabels:
        os: windows
        arch: amd64
    bin: kubectl-portal.exe
    {{addURIAndSha "https://github.com/federicotdn/kubectl-portal/releases/download/{{ .TagName }}/kubectl-portal_{{ .TagName }}_windows_amd64.tar.gz" .TagName }}
